#!/bin/bash
set -e
echo "=== GPU Info ==="
rocminfo 2>/dev/null | grep -E 'gfx|Name:.*Device' | head -10 || echo "rocminfo not found"
echo ""
echo "=== ROCm SMI ==="
rocm-smi --showid 2>/dev/null | head -15 || echo "rocm-smi not found"
echo ""
echo "=== hipcc version ==="
hipcc --version 2>/dev/null | head -5 || echo "hipcc not found"
echo ""
echo "=== PyTorch ==="
python3 -c "import torch; print(f'torch={torch.__version__}, hip={torch.version.hip}, cuda_avail={torch.cuda.is_available()}')" 2>/dev/null || echo "PyTorch not found"
echo ""
echo "=== ROCm path ==="
ls -la /opt/rocm*/lib/libamdhip64.so 2>/dev/null | head -3 || echo "ROCm libs not found"
echo ""
echo "=== pip packages ==="
pip list 2>/dev/null | grep -iE "torch|rocm|hip" | head -10 || echo "pip not available"
echo ""
echo "=== DONE ==="
